[package]
name = "zerompk"
description = "A zero-copy, zero-dependency, no_std-compatible, extremely fast MessagePack serializer for Rust."
version = "0.6.0"
edition = "2024"
readme = "../README.md"
license = "MIT"
repository = "https://github.com/nuskey8/zerompk"
documentation = "https://docs.rs/zerompk"
keywords = ["messagepack", "msgpack"]
categories = ["parsing", "no-std"]

[features]
default = ["std"]
std = []
derive = ["dep:zerompk_derive"]
default-as-map = ["derive", "zerompk_derive/default-as-map"]
default-vec-u8-as-array = ["derive", "zerompk_derive/default-vec-u8-as-array"]
chrono = ["dep:chrono"]
bytes = ["dep:bytes"]
uuid = ["dep:uuid"]
preserve-int-width = []

[dependencies]
zerompk_derive = { version = "0.6.0", path = "../zerompk_derive", optional = true }
chrono = { version = "0.4", default-features = false, features = [
    "alloc",
], optional = true }
bytes = { version = "1", default-features = false, optional = true }
uuid = { version = "1", default-features = false, optional = true }

[dev-dependencies]
rmp-serde = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
zerompk_derive = { path = "../zerompk_derive" }
chrono = "0.4"
serde_json = "1.0.149"
serde_bytes = "0.11.19"
msgpacker = "0.7.1"
